[tasks.test]
description = "Run all tests"
command = "cargo"
args = ["test"]

[tasks.build]
description = "Build wasm"
command = "wasm-pack"
args = ["build","--target","web"]
dependencies = ["test"]

[tasks.update]
description = "Build wasm and update package"
script = "cd pkg && yarn pack && mv euler-engine*.tgz ../../euler-editor/pkg"
# dependencies = ["build"]